parameters:
#    hollo_layout.example.class: Hollo\LayoutBundle\Example

services:
#    hollo_layout.example:
#        class: %hollo_layout.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
